<?php

declare(strict_types=1);

namespace DSuurlant\Response2Schema\Spec;

final class DefaultSpec
{
    /**
     * Retrieve a default OpenAPI spec with the given resource schema injected into the components attribute.
     */
    public static function default(array $resourceSchema): array
    {
        return [
            'openapi' => '3.0.3',
            'info' => [
                'title' => 'OpenAPI specification automatically generated by Response2Schema.',
                'version' => '1.0.0',
                'description' => 'Please adapt this specification to your own needs.'
            ],
            'paths' => [
                '/resource' => [
                    'get' => [
                        'description' => 'Description of the endpoint',
                        'operationId' => 'getResource',
                        'responses' => [
                            '200' => [
                                'description' => 'Description of this response.',
                                'content' => [
                                    'application/json' => [
                                        'schema' => [
                                            '$ref' => '#/components/schemas/Resource'
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ],
            'components' => [
                'schemas' => [
                    'Resource' => $resourceSchema
                ]
            ]
        ];
    }
}
